/**
 * ISO-3166 alpha-2 country list for the registration country picker.
 *
 * Zero-dependency static dataset. Codes feed `countryFlag(code)` from
 * `@/lib/flags`. Ghana is listed first so it can serve as the default
 * selection. Coverage spans every African nation plus the major world
 * markets (~120 entries).
 */
export interface Country {
  name: string;
  /** ISO-3166-1 alpha-2 code (uppercase). */
  code: string;
}

export const COUNTRIES: Country[] = [
  { name: "Ghana", code: "GH" },
  { name: "Nigeria", code: "NG" },
  { name: "Kenya", code: "KE" },
  { name: "South Africa", code: "ZA" },
  { name: "Tanzania", code: "TZ" },
  { name: "Uganda", code: "UG" },
  { name: "Ethiopia", code: "ET" },
  { name: "Egypt", code: "EG" },
  { name: "Morocco", code: "MA" },
  { name: "Algeria", code: "DZ" },
  { name: "Tunisia", code: "TN" },
  { name: "Libya", code: "LY" },
  { name: "Sudan", code: "SD" },
  { name: "South Sudan", code: "SS" },
  { name: "Senegal", code: "SN" },
  { name: "Côte d’Ivoire", code: "CI" },
  { name: "Cameroon", code: "CM" },
  { name: "Angola", code: "AO" },
  { name: "Mozambique", code: "MZ" },
  { name: "Zambia", code: "ZM" },
  { name: "Zimbabwe", code: "ZW" },
  { name: "Botswana", code: "BW" },
  { name: "Namibia", code: "NA" },
  { name: "Rwanda", code: "RW" },
  { name: "Burundi", code: "BI" },
  { name: "Benin", code: "BJ" },
  { name: "Togo", code: "TG" },
  { name: "Burkina Faso", code: "BF" },
  { name: "Mali", code: "ML" },
  { name: "Niger", code: "NE" },
  { name: "Guinea", code: "GN" },
  { name: "Guinea-Bissau", code: "GW" },
  { name: "Sierra Leone", code: "SL" },
  { name: "Liberia", code: "LR" },
  { name: "Gambia", code: "GM" },
  { name: "Mauritania", code: "MR" },
  { name: "Chad", code: "TD" },
  { name: "Central African Republic", code: "CF" },
  { name: "Congo (Brazzaville)", code: "CG" },
  { name: "Congo (Kinshasa)", code: "CD" },
  { name: "Gabon", code: "GA" },
  { name: "Equatorial Guinea", code: "GQ" },
  { name: "Eritrea", code: "ER" },
  { name: "Djibouti", code: "DJ" },
  { name: "Somalia", code: "SO" },
  { name: "Malawi", code: "MW" },
  { name: "Lesotho", code: "LS" },
  { name: "Eswatini", code: "SZ" },
  { name: "Madagascar", code: "MG" },
  { name: "Mauritius", code: "MU" },
  { name: "Seychelles", code: "SC" },
  { name: "Cabo Verde", code: "CV" },
  { name: "Comoros", code: "KM" },
  { name: "São Tomé and Príncipe", code: "ST" },
  { name: "United Kingdom", code: "GB" },
  { name: "Ireland", code: "IE" },
  { name: "United States", code: "US" },
  { name: "Canada", code: "CA" },
  { name: "Mexico", code: "MX" },
  { name: "Brazil", code: "BR" },
  { name: "Argentina", code: "AR" },
  { name: "Chile", code: "CL" },
  { name: "Colombia", code: "CO" },
  { name: "Peru", code: "PE" },
  { name: "Venezuela", code: "VE" },
  { name: "Jamaica", code: "JM" },
  { name: "Trinidad and Tobago", code: "TT" },
  { name: "France", code: "FR" },
  { name: "Germany", code: "DE" },
  { name: "Spain", code: "ES" },
  { name: "Portugal", code: "PT" },
  { name: "Italy", code: "IT" },
  { name: "Netherlands", code: "NL" },
  { name: "Belgium", code: "BE" },
  { name: "Switzerland", code: "CH" },
  { name: "Austria", code: "AT" },
  { name: "Sweden", code: "SE" },
  { name: "Norway", code: "NO" },
  { name: "Denmark", code: "DK" },
  { name: "Finland", code: "FI" },
  { name: "Iceland", code: "IS" },
  { name: "Poland", code: "PL" },
  { name: "Czechia", code: "CZ" },
  { name: "Slovakia", code: "SK" },
  { name: "Hungary", code: "HU" },
  { name: "Romania", code: "RO" },
  { name: "Bulgaria", code: "BG" },
  { name: "Greece", code: "GR" },
  { name: "Croatia", code: "HR" },
  { name: "Serbia", code: "RS" },
  { name: "Ukraine", code: "UA" },
  { name: "Russia", code: "RU" },
  { name: "Turkey", code: "TR" },
  { name: "Saudi Arabia", code: "SA" },
  { name: "United Arab Emirates", code: "AE" },
  { name: "Qatar", code: "QA" },
  { name: "Kuwait", code: "KW" },
  { name: "Bahrain", code: "BH" },
  { name: "Oman", code: "OM" },
  { name: "Jordan", code: "JO" },
  { name: "Lebanon", code: "LB" },
  { name: "Israel", code: "IL" },
  { name: "Iraq", code: "IQ" },
  { name: "Iran", code: "IR" },
  { name: "Pakistan", code: "PK" },
  { name: "India", code: "IN" },
  { name: "Bangladesh", code: "BD" },
  { name: "Sri Lanka", code: "LK" },
  { name: "Nepal", code: "NP" },
  { name: "Afghanistan", code: "AF" },
  { name: "China", code: "CN" },
  { name: "Japan", code: "JP" },
  { name: "South Korea", code: "KR" },
  { name: "Taiwan", code: "TW" },
  { name: "Hong Kong", code: "HK" },
  { name: "Singapore", code: "SG" },
  { name: "Malaysia", code: "MY" },
  { name: "Indonesia", code: "ID" },
  { name: "Philippines", code: "PH" },
  { name: "Thailand", code: "TH" },
  { name: "Vietnam", code: "VN" },
  { name: "Australia", code: "AU" },
  { name: "New Zealand", code: "NZ" },
];

/** Default registration country. */
export const DEFAULT_COUNTRY_CODE = "GH";

/** Look up a country by its ISO alpha-2 code. */
export function findCountry(code: string): Country | undefined {
  return COUNTRIES.find((c) => c.code === code);
}
