/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RefundRouteImport } from './routes/refund'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HelpRouteImport } from './routes/help'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuizSessionIdRouteImport } from './routes/quiz.$sessionId'
import { Route as PaymentCallbackRouteImport } from './routes/payment.callback'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTransactionsRouteImport } from './routes/admin.transactions'
import { Route as AdminSubscriptionsRouteImport } from './routes/admin.subscriptions'
import { Route as AdminRolesRouteImport } from './routes/admin.roles'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminQuestionsRouteImport } from './routes/admin.questions'
import { Route as AdminProfileRouteImport } from './routes/admin.profile'
import { Route as AdminNotesRouteImport } from './routes/admin.notes'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminFlagsRouteImport } from './routes/admin.flags'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminBanksRouteImport } from './routes/admin.banks'
import { Route as AdminAuditLogsRouteImport } from './routes/admin.audit-logs'
import { Route as AdminApiRouteImport } from './routes/admin.api'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminAiSettingsRouteImport } from './routes/admin.ai-settings'
import { Route as AppSubscriptionRouteImport } from './routes/_app.subscription'
import { Route as AppSessionsRouteImport } from './routes/_app.sessions'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppNotesRouteImport } from './routes/_app.notes'
import { Route as AppLeaderboardRouteImport } from './routes/_app.leaderboard'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppBanksRouteImport } from './routes/_app.banks'
import { Route as AppAnalyticsRouteImport } from './routes/_app.analytics'
import { Route as QuizConfigureBankIdRouteImport } from './routes/quiz.configure.$bankId'
import { Route as QuizSessionIdReviewRouteImport } from './routes/quiz.$sessionId.review'
import { Route as QuizSessionIdResultsRouteImport } from './routes/quiz.$sessionId.results'
import { Route as AdminUsersUserIdRouteImport } from './routes/admin.users.$userId'
import { Route as AdminSettingsSystemRouteImport } from './routes/admin.settings.system'
import { Route as AdminSettingsPricingRouteImport } from './routes/admin.settings.pricing'
import { Route as AdminSettingsPlansRouteImport } from './routes/admin.settings.plans'
import { Route as AdminQuestionsCreateRouteImport } from './routes/admin.questions.create'
import { Route as AdminBanksCreateRouteImport } from './routes/admin.banks.create'
import { Route as AdminBanksBankIdUploadRouteImport } from './routes/admin.banks.$bankId.upload'
import { Route as AdminBanksBankIdQuestionsRouteImport } from './routes/admin.banks.$bankId.questions'
import { Route as AdminBanksBankIdEditRouteImport } from './routes/admin.banks.$bankId.edit'
import { Route as AdminBanksBankIdQuestionsNewRouteImport } from './routes/admin.banks.$bankId.questions.new'
import { Route as AdminBanksBankIdQuestionsQuestionIdRouteImport } from './routes/admin.banks.$bankId.questions.$questionId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundRoute = RefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizSessionIdRoute = QuizSessionIdRouteImport.update({
  id: '/quiz/$sessionId',
  path: '/quiz/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentCallbackRoute = PaymentCallbackRouteImport.update({
  id: '/payment/callback',
  path: '/payment/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTransactionsRoute = AdminTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubscriptionsRoute = AdminSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQuestionsRoute = AdminQuestionsRouteImport.update({
  id: '/questions',
  path: '/questions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotesRoute = AdminNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFlagsRoute = AdminFlagsRouteImport.update({
  id: '/flags',
  path: '/flags',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBanksRoute = AdminBanksRouteImport.update({
  id: '/banks',
  path: '/banks',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditLogsRoute = AdminAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApiRoute = AdminApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAiSettingsRoute = AdminAiSettingsRouteImport.update({
  id: '/ai-settings',
  path: '/ai-settings',
  getParentRoute: () => AdminRoute,
} as any)
const AppSubscriptionRoute = AppSubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => AppRoute,
} as any)
const AppSessionsRoute = AppSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppNotesRoute = AppNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaderboardRoute = AppLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppBanksRoute = AppBanksRouteImport.update({
  id: '/banks',
  path: '/banks',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const QuizConfigureBankIdRoute = QuizConfigureBankIdRouteImport.update({
  id: '/quiz/configure/$bankId',
  path: '/quiz/configure/$bankId',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizSessionIdReviewRoute = QuizSessionIdReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => QuizSessionIdRoute,
} as any)
const QuizSessionIdResultsRoute = QuizSessionIdResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => QuizSessionIdRoute,
} as any)
const AdminUsersUserIdRoute = AdminUsersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => AdminUsersRoute,
} as any)
const AdminSettingsSystemRoute = AdminSettingsSystemRouteImport.update({
  id: '/settings/system',
  path: '/settings/system',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsPricingRoute = AdminSettingsPricingRouteImport.update({
  id: '/settings/pricing',
  path: '/settings/pricing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsPlansRoute = AdminSettingsPlansRouteImport.update({
  id: '/settings/plans',
  path: '/settings/plans',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQuestionsCreateRoute = AdminQuestionsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AdminQuestionsRoute,
} as any)
const AdminBanksCreateRoute = AdminBanksCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AdminBanksRoute,
} as any)
const AdminBanksBankIdUploadRoute = AdminBanksBankIdUploadRouteImport.update({
  id: '/$bankId/upload',
  path: '/$bankId/upload',
  getParentRoute: () => AdminBanksRoute,
} as any)
const AdminBanksBankIdQuestionsRoute =
  AdminBanksBankIdQuestionsRouteImport.update({
    id: '/$bankId/questions',
    path: '/$bankId/questions',
    getParentRoute: () => AdminBanksRoute,
  } as any)
const AdminBanksBankIdEditRoute = AdminBanksBankIdEditRouteImport.update({
  id: '/$bankId/edit',
  path: '/$bankId/edit',
  getParentRoute: () => AdminBanksRoute,
} as any)
const AdminBanksBankIdQuestionsNewRoute =
  AdminBanksBankIdQuestionsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AdminBanksBankIdQuestionsRoute,
  } as any)
const AdminBanksBankIdQuestionsQuestionIdRoute =
  AdminBanksBankIdQuestionsQuestionIdRouteImport.update({
    id: '/$questionId',
    path: '/$questionId',
    getParentRoute: () => AdminBanksBankIdQuestionsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/analytics': typeof AppAnalyticsRoute
  '/banks': typeof AppBanksRoute
  '/dashboard': typeof AppDashboardRoute
  '/leaderboard': typeof AppLeaderboardRoute
  '/notes': typeof AppNotesRoute
  '/notifications': typeof AppNotificationsRoute
  '/profile': typeof AppProfileRoute
  '/sessions': typeof AppSessionsRoute
  '/subscription': typeof AppSubscriptionRoute
  '/admin/ai-settings': typeof AdminAiSettingsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/api': typeof AdminApiRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/banks': typeof AdminBanksRouteWithChildren
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/flags': typeof AdminFlagsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/notes': typeof AdminNotesRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/questions': typeof AdminQuestionsRouteWithChildren
  '/admin/reports': typeof AdminReportsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/payment/callback': typeof PaymentCallbackRoute
  '/quiz/$sessionId': typeof QuizSessionIdRouteWithChildren
  '/admin/banks/create': typeof AdminBanksCreateRoute
  '/admin/questions/create': typeof AdminQuestionsCreateRoute
  '/admin/settings/plans': typeof AdminSettingsPlansRoute
  '/admin/settings/pricing': typeof AdminSettingsPricingRoute
  '/admin/settings/system': typeof AdminSettingsSystemRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/quiz/$sessionId/results': typeof QuizSessionIdResultsRoute
  '/quiz/$sessionId/review': typeof QuizSessionIdReviewRoute
  '/quiz/configure/$bankId': typeof QuizConfigureBankIdRoute
  '/admin/banks/$bankId/edit': typeof AdminBanksBankIdEditRoute
  '/admin/banks/$bankId/questions': typeof AdminBanksBankIdQuestionsRouteWithChildren
  '/admin/banks/$bankId/upload': typeof AdminBanksBankIdUploadRoute
  '/admin/banks/$bankId/questions/$questionId': typeof AdminBanksBankIdQuestionsQuestionIdRoute
  '/admin/banks/$bankId/questions/new': typeof AdminBanksBankIdQuestionsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/analytics': typeof AppAnalyticsRoute
  '/banks': typeof AppBanksRoute
  '/dashboard': typeof AppDashboardRoute
  '/leaderboard': typeof AppLeaderboardRoute
  '/notes': typeof AppNotesRoute
  '/notifications': typeof AppNotificationsRoute
  '/profile': typeof AppProfileRoute
  '/sessions': typeof AppSessionsRoute
  '/subscription': typeof AppSubscriptionRoute
  '/admin/ai-settings': typeof AdminAiSettingsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/api': typeof AdminApiRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/banks': typeof AdminBanksRouteWithChildren
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/flags': typeof AdminFlagsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/notes': typeof AdminNotesRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/questions': typeof AdminQuestionsRouteWithChildren
  '/admin/reports': typeof AdminReportsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/payment/callback': typeof PaymentCallbackRoute
  '/quiz/$sessionId': typeof QuizSessionIdRouteWithChildren
  '/admin/banks/create': typeof AdminBanksCreateRoute
  '/admin/questions/create': typeof AdminQuestionsCreateRoute
  '/admin/settings/plans': typeof AdminSettingsPlansRoute
  '/admin/settings/pricing': typeof AdminSettingsPricingRoute
  '/admin/settings/system': typeof AdminSettingsSystemRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/quiz/$sessionId/results': typeof QuizSessionIdResultsRoute
  '/quiz/$sessionId/review': typeof QuizSessionIdReviewRoute
  '/quiz/configure/$bankId': typeof QuizConfigureBankIdRoute
  '/admin/banks/$bankId/edit': typeof AdminBanksBankIdEditRoute
  '/admin/banks/$bankId/questions': typeof AdminBanksBankIdQuestionsRouteWithChildren
  '/admin/banks/$bankId/upload': typeof AdminBanksBankIdUploadRoute
  '/admin/banks/$bankId/questions/$questionId': typeof AdminBanksBankIdQuestionsQuestionIdRoute
  '/admin/banks/$bankId/questions/new': typeof AdminBanksBankIdQuestionsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/banks': typeof AppBanksRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/leaderboard': typeof AppLeaderboardRoute
  '/_app/notes': typeof AppNotesRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/sessions': typeof AppSessionsRoute
  '/_app/subscription': typeof AppSubscriptionRoute
  '/admin/ai-settings': typeof AdminAiSettingsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/api': typeof AdminApiRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/banks': typeof AdminBanksRouteWithChildren
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/flags': typeof AdminFlagsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/notes': typeof AdminNotesRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/questions': typeof AdminQuestionsRouteWithChildren
  '/admin/reports': typeof AdminReportsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/payment/callback': typeof PaymentCallbackRoute
  '/quiz/$sessionId': typeof QuizSessionIdRouteWithChildren
  '/admin/banks/create': typeof AdminBanksCreateRoute
  '/admin/questions/create': typeof AdminQuestionsCreateRoute
  '/admin/settings/plans': typeof AdminSettingsPlansRoute
  '/admin/settings/pricing': typeof AdminSettingsPricingRoute
  '/admin/settings/system': typeof AdminSettingsSystemRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/quiz/$sessionId/results': typeof QuizSessionIdResultsRoute
  '/quiz/$sessionId/review': typeof QuizSessionIdReviewRoute
  '/quiz/configure/$bankId': typeof QuizConfigureBankIdRoute
  '/admin/banks/$bankId/edit': typeof AdminBanksBankIdEditRoute
  '/admin/banks/$bankId/questions': typeof AdminBanksBankIdQuestionsRouteWithChildren
  '/admin/banks/$bankId/upload': typeof AdminBanksBankIdUploadRoute
  '/admin/banks/$bankId/questions/$questionId': typeof AdminBanksBankIdQuestionsQuestionIdRoute
  '/admin/banks/$bankId/questions/new': typeof AdminBanksBankIdQuestionsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/faq'
    | '/forgot-password'
    | '/help'
    | '/login'
    | '/onboarding'
    | '/pricing'
    | '/privacy'
    | '/refund'
    | '/reset-password'
    | '/terms'
    | '/analytics'
    | '/banks'
    | '/dashboard'
    | '/leaderboard'
    | '/notes'
    | '/notifications'
    | '/profile'
    | '/sessions'
    | '/subscription'
    | '/admin/ai-settings'
    | '/admin/analytics'
    | '/admin/api'
    | '/admin/audit-logs'
    | '/admin/banks'
    | '/admin/categories'
    | '/admin/dashboard'
    | '/admin/flags'
    | '/admin/login'
    | '/admin/notes'
    | '/admin/profile'
    | '/admin/questions'
    | '/admin/reports'
    | '/admin/roles'
    | '/admin/subscriptions'
    | '/admin/transactions'
    | '/admin/users'
    | '/auth/callback'
    | '/payment/callback'
    | '/quiz/$sessionId'
    | '/admin/banks/create'
    | '/admin/questions/create'
    | '/admin/settings/plans'
    | '/admin/settings/pricing'
    | '/admin/settings/system'
    | '/admin/users/$userId'
    | '/quiz/$sessionId/results'
    | '/quiz/$sessionId/review'
    | '/quiz/configure/$bankId'
    | '/admin/banks/$bankId/edit'
    | '/admin/banks/$bankId/questions'
    | '/admin/banks/$bankId/upload'
    | '/admin/banks/$bankId/questions/$questionId'
    | '/admin/banks/$bankId/questions/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/faq'
    | '/forgot-password'
    | '/help'
    | '/login'
    | '/onboarding'
    | '/pricing'
    | '/privacy'
    | '/refund'
    | '/reset-password'
    | '/terms'
    | '/analytics'
    | '/banks'
    | '/dashboard'
    | '/leaderboard'
    | '/notes'
    | '/notifications'
    | '/profile'
    | '/sessions'
    | '/subscription'
    | '/admin/ai-settings'
    | '/admin/analytics'
    | '/admin/api'
    | '/admin/audit-logs'
    | '/admin/banks'
    | '/admin/categories'
    | '/admin/dashboard'
    | '/admin/flags'
    | '/admin/login'
    | '/admin/notes'
    | '/admin/profile'
    | '/admin/questions'
    | '/admin/reports'
    | '/admin/roles'
    | '/admin/subscriptions'
    | '/admin/transactions'
    | '/admin/users'
    | '/auth/callback'
    | '/payment/callback'
    | '/quiz/$sessionId'
    | '/admin/banks/create'
    | '/admin/questions/create'
    | '/admin/settings/plans'
    | '/admin/settings/pricing'
    | '/admin/settings/system'
    | '/admin/users/$userId'
    | '/quiz/$sessionId/results'
    | '/quiz/$sessionId/review'
    | '/quiz/configure/$bankId'
    | '/admin/banks/$bankId/edit'
    | '/admin/banks/$bankId/questions'
    | '/admin/banks/$bankId/upload'
    | '/admin/banks/$bankId/questions/$questionId'
    | '/admin/banks/$bankId/questions/new'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/about'
    | '/admin'
    | '/contact'
    | '/faq'
    | '/forgot-password'
    | '/help'
    | '/login'
    | '/onboarding'
    | '/pricing'
    | '/privacy'
    | '/refund'
    | '/reset-password'
    | '/terms'
    | '/_app/analytics'
    | '/_app/banks'
    | '/_app/dashboard'
    | '/_app/leaderboard'
    | '/_app/notes'
    | '/_app/notifications'
    | '/_app/profile'
    | '/_app/sessions'
    | '/_app/subscription'
    | '/admin/ai-settings'
    | '/admin/analytics'
    | '/admin/api'
    | '/admin/audit-logs'
    | '/admin/banks'
    | '/admin/categories'
    | '/admin/dashboard'
    | '/admin/flags'
    | '/admin/login'
    | '/admin/notes'
    | '/admin/profile'
    | '/admin/questions'
    | '/admin/reports'
    | '/admin/roles'
    | '/admin/subscriptions'
    | '/admin/transactions'
    | '/admin/users'
    | '/auth/callback'
    | '/payment/callback'
    | '/quiz/$sessionId'
    | '/admin/banks/create'
    | '/admin/questions/create'
    | '/admin/settings/plans'
    | '/admin/settings/pricing'
    | '/admin/settings/system'
    | '/admin/users/$userId'
    | '/quiz/$sessionId/results'
    | '/quiz/$sessionId/review'
    | '/quiz/configure/$bankId'
    | '/admin/banks/$bankId/edit'
    | '/admin/banks/$bankId/questions'
    | '/admin/banks/$bankId/upload'
    | '/admin/banks/$bankId/questions/$questionId'
    | '/admin/banks/$bankId/questions/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HelpRoute: typeof HelpRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundRoute: typeof RefundRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsRoute: typeof TermsRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  PaymentCallbackRoute: typeof PaymentCallbackRoute
  QuizSessionIdRoute: typeof QuizSessionIdRouteWithChildren
  QuizConfigureBankIdRoute: typeof QuizConfigureBankIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund': {
      id: '/refund'
      path: '/refund'
      fullPath: '/refund'
      preLoaderRoute: typeof RefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/$sessionId': {
      id: '/quiz/$sessionId'
      path: '/quiz/$sessionId'
      fullPath: '/quiz/$sessionId'
      preLoaderRoute: typeof QuizSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/callback': {
      id: '/payment/callback'
      path: '/payment/callback'
      fullPath: '/payment/callback'
      preLoaderRoute: typeof PaymentCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/transactions': {
      id: '/admin/transactions'
      path: '/transactions'
      fullPath: '/admin/transactions'
      preLoaderRoute: typeof AdminTransactionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/subscriptions': {
      id: '/admin/subscriptions'
      path: '/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AdminSubscriptionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/questions': {
      id: '/admin/questions'
      path: '/questions'
      fullPath: '/admin/questions'
      preLoaderRoute: typeof AdminQuestionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notes': {
      id: '/admin/notes'
      path: '/notes'
      fullPath: '/admin/notes'
      preLoaderRoute: typeof AdminNotesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/flags': {
      id: '/admin/flags'
      path: '/flags'
      fullPath: '/admin/flags'
      preLoaderRoute: typeof AdminFlagsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/banks': {
      id: '/admin/banks'
      path: '/banks'
      fullPath: '/admin/banks'
      preLoaderRoute: typeof AdminBanksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit-logs': {
      id: '/admin/audit-logs'
      path: '/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AdminAuditLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/api': {
      id: '/admin/api'
      path: '/api'
      fullPath: '/admin/api'
      preLoaderRoute: typeof AdminApiRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ai-settings': {
      id: '/admin/ai-settings'
      path: '/ai-settings'
      fullPath: '/admin/ai-settings'
      preLoaderRoute: typeof AdminAiSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_app/subscription': {
      id: '/_app/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof AppSubscriptionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sessions': {
      id: '/_app/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof AppSessionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notes': {
      id: '/_app/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof AppNotesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leaderboard': {
      id: '/_app/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AppLeaderboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/banks': {
      id: '/_app/banks'
      path: '/banks'
      fullPath: '/banks'
      preLoaderRoute: typeof AppBanksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/quiz/configure/$bankId': {
      id: '/quiz/configure/$bankId'
      path: '/quiz/configure/$bankId'
      fullPath: '/quiz/configure/$bankId'
      preLoaderRoute: typeof QuizConfigureBankIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/$sessionId/review': {
      id: '/quiz/$sessionId/review'
      path: '/review'
      fullPath: '/quiz/$sessionId/review'
      preLoaderRoute: typeof QuizSessionIdReviewRouteImport
      parentRoute: typeof QuizSessionIdRoute
    }
    '/quiz/$sessionId/results': {
      id: '/quiz/$sessionId/results'
      path: '/results'
      fullPath: '/quiz/$sessionId/results'
      preLoaderRoute: typeof QuizSessionIdResultsRouteImport
      parentRoute: typeof QuizSessionIdRoute
    }
    '/admin/users/$userId': {
      id: '/admin/users/$userId'
      path: '/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AdminUsersUserIdRouteImport
      parentRoute: typeof AdminUsersRoute
    }
    '/admin/settings/system': {
      id: '/admin/settings/system'
      path: '/settings/system'
      fullPath: '/admin/settings/system'
      preLoaderRoute: typeof AdminSettingsSystemRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings/pricing': {
      id: '/admin/settings/pricing'
      path: '/settings/pricing'
      fullPath: '/admin/settings/pricing'
      preLoaderRoute: typeof AdminSettingsPricingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings/plans': {
      id: '/admin/settings/plans'
      path: '/settings/plans'
      fullPath: '/admin/settings/plans'
      preLoaderRoute: typeof AdminSettingsPlansRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/questions/create': {
      id: '/admin/questions/create'
      path: '/create'
      fullPath: '/admin/questions/create'
      preLoaderRoute: typeof AdminQuestionsCreateRouteImport
      parentRoute: typeof AdminQuestionsRoute
    }
    '/admin/banks/create': {
      id: '/admin/banks/create'
      path: '/create'
      fullPath: '/admin/banks/create'
      preLoaderRoute: typeof AdminBanksCreateRouteImport
      parentRoute: typeof AdminBanksRoute
    }
    '/admin/banks/$bankId/upload': {
      id: '/admin/banks/$bankId/upload'
      path: '/$bankId/upload'
      fullPath: '/admin/banks/$bankId/upload'
      preLoaderRoute: typeof AdminBanksBankIdUploadRouteImport
      parentRoute: typeof AdminBanksRoute
    }
    '/admin/banks/$bankId/questions': {
      id: '/admin/banks/$bankId/questions'
      path: '/$bankId/questions'
      fullPath: '/admin/banks/$bankId/questions'
      preLoaderRoute: typeof AdminBanksBankIdQuestionsRouteImport
      parentRoute: typeof AdminBanksRoute
    }
    '/admin/banks/$bankId/edit': {
      id: '/admin/banks/$bankId/edit'
      path: '/$bankId/edit'
      fullPath: '/admin/banks/$bankId/edit'
      preLoaderRoute: typeof AdminBanksBankIdEditRouteImport
      parentRoute: typeof AdminBanksRoute
    }
    '/admin/banks/$bankId/questions/new': {
      id: '/admin/banks/$bankId/questions/new'
      path: '/new'
      fullPath: '/admin/banks/$bankId/questions/new'
      preLoaderRoute: typeof AdminBanksBankIdQuestionsNewRouteImport
      parentRoute: typeof AdminBanksBankIdQuestionsRoute
    }
    '/admin/banks/$bankId/questions/$questionId': {
      id: '/admin/banks/$bankId/questions/$questionId'
      path: '/$questionId'
      fullPath: '/admin/banks/$bankId/questions/$questionId'
      preLoaderRoute: typeof AdminBanksBankIdQuestionsQuestionIdRouteImport
      parentRoute: typeof AdminBanksBankIdQuestionsRoute
    }
  }
}

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppBanksRoute: typeof AppBanksRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppLeaderboardRoute: typeof AppLeaderboardRoute
  AppNotesRoute: typeof AppNotesRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSessionsRoute: typeof AppSessionsRoute
  AppSubscriptionRoute: typeof AppSubscriptionRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppBanksRoute: AppBanksRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppLeaderboardRoute: AppLeaderboardRoute,
  AppNotesRoute: AppNotesRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppProfileRoute: AppProfileRoute,
  AppSessionsRoute: AppSessionsRoute,
  AppSubscriptionRoute: AppSubscriptionRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AdminBanksBankIdQuestionsRouteChildren {
  AdminBanksBankIdQuestionsQuestionIdRoute: typeof AdminBanksBankIdQuestionsQuestionIdRoute
  AdminBanksBankIdQuestionsNewRoute: typeof AdminBanksBankIdQuestionsNewRoute
}

const AdminBanksBankIdQuestionsRouteChildren: AdminBanksBankIdQuestionsRouteChildren =
  {
    AdminBanksBankIdQuestionsQuestionIdRoute:
      AdminBanksBankIdQuestionsQuestionIdRoute,
    AdminBanksBankIdQuestionsNewRoute: AdminBanksBankIdQuestionsNewRoute,
  }

const AdminBanksBankIdQuestionsRouteWithChildren =
  AdminBanksBankIdQuestionsRoute._addFileChildren(
    AdminBanksBankIdQuestionsRouteChildren,
  )

interface AdminBanksRouteChildren {
  AdminBanksCreateRoute: typeof AdminBanksCreateRoute
  AdminBanksBankIdEditRoute: typeof AdminBanksBankIdEditRoute
  AdminBanksBankIdQuestionsRoute: typeof AdminBanksBankIdQuestionsRouteWithChildren
  AdminBanksBankIdUploadRoute: typeof AdminBanksBankIdUploadRoute
}

const AdminBanksRouteChildren: AdminBanksRouteChildren = {
  AdminBanksCreateRoute: AdminBanksCreateRoute,
  AdminBanksBankIdEditRoute: AdminBanksBankIdEditRoute,
  AdminBanksBankIdQuestionsRoute: AdminBanksBankIdQuestionsRouteWithChildren,
  AdminBanksBankIdUploadRoute: AdminBanksBankIdUploadRoute,
}

const AdminBanksRouteWithChildren = AdminBanksRoute._addFileChildren(
  AdminBanksRouteChildren,
)

interface AdminQuestionsRouteChildren {
  AdminQuestionsCreateRoute: typeof AdminQuestionsCreateRoute
}

const AdminQuestionsRouteChildren: AdminQuestionsRouteChildren = {
  AdminQuestionsCreateRoute: AdminQuestionsCreateRoute,
}

const AdminQuestionsRouteWithChildren = AdminQuestionsRoute._addFileChildren(
  AdminQuestionsRouteChildren,
)

interface AdminUsersRouteChildren {
  AdminUsersUserIdRoute: typeof AdminUsersUserIdRoute
}

const AdminUsersRouteChildren: AdminUsersRouteChildren = {
  AdminUsersUserIdRoute: AdminUsersUserIdRoute,
}

const AdminUsersRouteWithChildren = AdminUsersRoute._addFileChildren(
  AdminUsersRouteChildren,
)

interface AdminRouteChildren {
  AdminAiSettingsRoute: typeof AdminAiSettingsRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminApiRoute: typeof AdminApiRoute
  AdminAuditLogsRoute: typeof AdminAuditLogsRoute
  AdminBanksRoute: typeof AdminBanksRouteWithChildren
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminFlagsRoute: typeof AdminFlagsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminNotesRoute: typeof AdminNotesRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminQuestionsRoute: typeof AdminQuestionsRouteWithChildren
  AdminReportsRoute: typeof AdminReportsRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminSubscriptionsRoute: typeof AdminSubscriptionsRoute
  AdminTransactionsRoute: typeof AdminTransactionsRoute
  AdminUsersRoute: typeof AdminUsersRouteWithChildren
  AdminSettingsPlansRoute: typeof AdminSettingsPlansRoute
  AdminSettingsPricingRoute: typeof AdminSettingsPricingRoute
  AdminSettingsSystemRoute: typeof AdminSettingsSystemRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAiSettingsRoute: AdminAiSettingsRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminApiRoute: AdminApiRoute,
  AdminAuditLogsRoute: AdminAuditLogsRoute,
  AdminBanksRoute: AdminBanksRouteWithChildren,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminFlagsRoute: AdminFlagsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminNotesRoute: AdminNotesRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminQuestionsRoute: AdminQuestionsRouteWithChildren,
  AdminReportsRoute: AdminReportsRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminSubscriptionsRoute: AdminSubscriptionsRoute,
  AdminTransactionsRoute: AdminTransactionsRoute,
  AdminUsersRoute: AdminUsersRouteWithChildren,
  AdminSettingsPlansRoute: AdminSettingsPlansRoute,
  AdminSettingsPricingRoute: AdminSettingsPricingRoute,
  AdminSettingsSystemRoute: AdminSettingsSystemRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface QuizSessionIdRouteChildren {
  QuizSessionIdResultsRoute: typeof QuizSessionIdResultsRoute
  QuizSessionIdReviewRoute: typeof QuizSessionIdReviewRoute
}

const QuizSessionIdRouteChildren: QuizSessionIdRouteChildren = {
  QuizSessionIdResultsRoute: QuizSessionIdResultsRoute,
  QuizSessionIdReviewRoute: QuizSessionIdReviewRoute,
}

const QuizSessionIdRouteWithChildren = QuizSessionIdRoute._addFileChildren(
  QuizSessionIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HelpRoute: HelpRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  RefundRoute: RefundRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsRoute: TermsRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  PaymentCallbackRoute: PaymentCallbackRoute,
  QuizSessionIdRoute: QuizSessionIdRouteWithChildren,
  QuizConfigureBankIdRoute: QuizConfigureBankIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
