/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuizSessionIdRouteImport } from './routes/quiz.$sessionId'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSubscriptionsRouteImport } from './routes/admin.subscriptions'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminFlagsRouteImport } from './routes/admin.flags'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminBanksRouteImport } from './routes/admin.banks'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AppSubscriptionRouteImport } from './routes/_app.subscription'
import { Route as AppSessionsRouteImport } from './routes/_app.sessions'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppLeaderboardRouteImport } from './routes/_app.leaderboard'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppBanksRouteImport } from './routes/_app.banks'
import { Route as AppAnalyticsRouteImport } from './routes/_app.analytics'
import { Route as QuizConfigureBankIdRouteImport } from './routes/quiz.configure.$bankId'
import { Route as QuizSessionIdReviewRouteImport } from './routes/quiz.$sessionId.review'
import { Route as QuizSessionIdResultsRouteImport } from './routes/quiz.$sessionId.results'
import { Route as AdminSettingsSystemRouteImport } from './routes/admin.settings.system'
import { Route as AdminSettingsPricingRouteImport } from './routes/admin.settings.pricing'
import { Route as AdminSettingsPlansRouteImport } from './routes/admin.settings.plans'
import { Route as AdminBanksBankIdUploadRouteImport } from './routes/admin.banks.$bankId.upload'
import { Route as AdminBanksBankIdQuestionsRouteImport } from './routes/admin.banks.$bankId.questions'

const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizSessionIdRoute = QuizSessionIdRouteImport.update({
  id: '/quiz/$sessionId',
  path: '/quiz/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubscriptionsRoute = AdminSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFlagsRoute = AdminFlagsRouteImport.update({
  id: '/flags',
  path: '/flags',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBanksRoute = AdminBanksRouteImport.update({
  id: '/banks',
  path: '/banks',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AppSubscriptionRoute = AppSubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => AppRoute,
} as any)
const AppSessionsRoute = AppSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaderboardRoute = AppLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppBanksRoute = AppBanksRouteImport.update({
  id: '/banks',
  path: '/banks',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const QuizConfigureBankIdRoute = QuizConfigureBankIdRouteImport.update({
  id: '/quiz/configure/$bankId',
  path: '/quiz/configure/$bankId',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizSessionIdReviewRoute = QuizSessionIdReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => QuizSessionIdRoute,
} as any)
const QuizSessionIdResultsRoute = QuizSessionIdResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => QuizSessionIdRoute,
} as any)
const AdminSettingsSystemRoute = AdminSettingsSystemRouteImport.update({
  id: '/settings/system',
  path: '/settings/system',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsPricingRoute = AdminSettingsPricingRouteImport.update({
  id: '/settings/pricing',
  path: '/settings/pricing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsPlansRoute = AdminSettingsPlansRouteImport.update({
  id: '/settings/plans',
  path: '/settings/plans',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBanksBankIdUploadRoute = AdminBanksBankIdUploadRouteImport.update({
  id: '/$bankId/upload',
  path: '/$bankId/upload',
  getParentRoute: () => AdminBanksRoute,
} as any)
const AdminBanksBankIdQuestionsRoute =
  AdminBanksBankIdQuestionsRouteImport.update({
    id: '/$bankId/questions',
    path: '/$bankId/questions',
    getParentRoute: () => AdminBanksRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/analytics': typeof AppAnalyticsRoute
  '/banks': typeof AppBanksRoute
  '/dashboard': typeof AppDashboardRoute
  '/leaderboard': typeof AppLeaderboardRoute
  '/profile': typeof AppProfileRoute
  '/sessions': typeof AppSessionsRoute
  '/subscription': typeof AppSubscriptionRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/banks': typeof AdminBanksRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/flags': typeof AdminFlagsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/quiz/$sessionId': typeof QuizSessionIdRouteWithChildren
  '/admin/settings/plans': typeof AdminSettingsPlansRoute
  '/admin/settings/pricing': typeof AdminSettingsPricingRoute
  '/admin/settings/system': typeof AdminSettingsSystemRoute
  '/quiz/$sessionId/results': typeof QuizSessionIdResultsRoute
  '/quiz/$sessionId/review': typeof QuizSessionIdReviewRoute
  '/quiz/configure/$bankId': typeof QuizConfigureBankIdRoute
  '/admin/banks/$bankId/questions': typeof AdminBanksBankIdQuestionsRoute
  '/admin/banks/$bankId/upload': typeof AdminBanksBankIdUploadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/analytics': typeof AppAnalyticsRoute
  '/banks': typeof AppBanksRoute
  '/dashboard': typeof AppDashboardRoute
  '/leaderboard': typeof AppLeaderboardRoute
  '/profile': typeof AppProfileRoute
  '/sessions': typeof AppSessionsRoute
  '/subscription': typeof AppSubscriptionRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/banks': typeof AdminBanksRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/flags': typeof AdminFlagsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/quiz/$sessionId': typeof QuizSessionIdRouteWithChildren
  '/admin/settings/plans': typeof AdminSettingsPlansRoute
  '/admin/settings/pricing': typeof AdminSettingsPricingRoute
  '/admin/settings/system': typeof AdminSettingsSystemRoute
  '/quiz/$sessionId/results': typeof QuizSessionIdResultsRoute
  '/quiz/$sessionId/review': typeof QuizSessionIdReviewRoute
  '/quiz/configure/$bankId': typeof QuizConfigureBankIdRoute
  '/admin/banks/$bankId/questions': typeof AdminBanksBankIdQuestionsRoute
  '/admin/banks/$bankId/upload': typeof AdminBanksBankIdUploadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/banks': typeof AppBanksRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/leaderboard': typeof AppLeaderboardRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/sessions': typeof AppSessionsRoute
  '/_app/subscription': typeof AppSubscriptionRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/banks': typeof AdminBanksRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/flags': typeof AdminFlagsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/quiz/$sessionId': typeof QuizSessionIdRouteWithChildren
  '/admin/settings/plans': typeof AdminSettingsPlansRoute
  '/admin/settings/pricing': typeof AdminSettingsPricingRoute
  '/admin/settings/system': typeof AdminSettingsSystemRoute
  '/quiz/$sessionId/results': typeof QuizSessionIdResultsRoute
  '/quiz/$sessionId/review': typeof QuizSessionIdReviewRoute
  '/quiz/configure/$bankId': typeof QuizConfigureBankIdRoute
  '/admin/banks/$bankId/questions': typeof AdminBanksBankIdQuestionsRoute
  '/admin/banks/$bankId/upload': typeof AdminBanksBankIdUploadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/login'
    | '/pricing'
    | '/analytics'
    | '/banks'
    | '/dashboard'
    | '/leaderboard'
    | '/profile'
    | '/sessions'
    | '/subscription'
    | '/admin/analytics'
    | '/admin/banks'
    | '/admin/dashboard'
    | '/admin/flags'
    | '/admin/login'
    | '/admin/subscriptions'
    | '/admin/users'
    | '/auth/callback'
    | '/quiz/$sessionId'
    | '/admin/settings/plans'
    | '/admin/settings/pricing'
    | '/admin/settings/system'
    | '/quiz/$sessionId/results'
    | '/quiz/$sessionId/review'
    | '/quiz/configure/$bankId'
    | '/admin/banks/$bankId/questions'
    | '/admin/banks/$bankId/upload'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/login'
    | '/pricing'
    | '/analytics'
    | '/banks'
    | '/dashboard'
    | '/leaderboard'
    | '/profile'
    | '/sessions'
    | '/subscription'
    | '/admin/analytics'
    | '/admin/banks'
    | '/admin/dashboard'
    | '/admin/flags'
    | '/admin/login'
    | '/admin/subscriptions'
    | '/admin/users'
    | '/auth/callback'
    | '/quiz/$sessionId'
    | '/admin/settings/plans'
    | '/admin/settings/pricing'
    | '/admin/settings/system'
    | '/quiz/$sessionId/results'
    | '/quiz/$sessionId/review'
    | '/quiz/configure/$bankId'
    | '/admin/banks/$bankId/questions'
    | '/admin/banks/$bankId/upload'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/about'
    | '/admin'
    | '/login'
    | '/pricing'
    | '/_app/analytics'
    | '/_app/banks'
    | '/_app/dashboard'
    | '/_app/leaderboard'
    | '/_app/profile'
    | '/_app/sessions'
    | '/_app/subscription'
    | '/admin/analytics'
    | '/admin/banks'
    | '/admin/dashboard'
    | '/admin/flags'
    | '/admin/login'
    | '/admin/subscriptions'
    | '/admin/users'
    | '/auth/callback'
    | '/quiz/$sessionId'
    | '/admin/settings/plans'
    | '/admin/settings/pricing'
    | '/admin/settings/system'
    | '/quiz/$sessionId/results'
    | '/quiz/$sessionId/review'
    | '/quiz/configure/$bankId'
    | '/admin/banks/$bankId/questions'
    | '/admin/banks/$bankId/upload'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  QuizSessionIdRoute: typeof QuizSessionIdRouteWithChildren
  QuizConfigureBankIdRoute: typeof QuizConfigureBankIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/$sessionId': {
      id: '/quiz/$sessionId'
      path: '/quiz/$sessionId'
      fullPath: '/quiz/$sessionId'
      preLoaderRoute: typeof QuizSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/subscriptions': {
      id: '/admin/subscriptions'
      path: '/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AdminSubscriptionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/flags': {
      id: '/admin/flags'
      path: '/flags'
      fullPath: '/admin/flags'
      preLoaderRoute: typeof AdminFlagsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/banks': {
      id: '/admin/banks'
      path: '/banks'
      fullPath: '/admin/banks'
      preLoaderRoute: typeof AdminBanksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_app/subscription': {
      id: '/_app/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof AppSubscriptionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sessions': {
      id: '/_app/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof AppSessionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leaderboard': {
      id: '/_app/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AppLeaderboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/banks': {
      id: '/_app/banks'
      path: '/banks'
      fullPath: '/banks'
      preLoaderRoute: typeof AppBanksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/quiz/configure/$bankId': {
      id: '/quiz/configure/$bankId'
      path: '/quiz/configure/$bankId'
      fullPath: '/quiz/configure/$bankId'
      preLoaderRoute: typeof QuizConfigureBankIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/$sessionId/review': {
      id: '/quiz/$sessionId/review'
      path: '/review'
      fullPath: '/quiz/$sessionId/review'
      preLoaderRoute: typeof QuizSessionIdReviewRouteImport
      parentRoute: typeof QuizSessionIdRoute
    }
    '/quiz/$sessionId/results': {
      id: '/quiz/$sessionId/results'
      path: '/results'
      fullPath: '/quiz/$sessionId/results'
      preLoaderRoute: typeof QuizSessionIdResultsRouteImport
      parentRoute: typeof QuizSessionIdRoute
    }
    '/admin/settings/system': {
      id: '/admin/settings/system'
      path: '/settings/system'
      fullPath: '/admin/settings/system'
      preLoaderRoute: typeof AdminSettingsSystemRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings/pricing': {
      id: '/admin/settings/pricing'
      path: '/settings/pricing'
      fullPath: '/admin/settings/pricing'
      preLoaderRoute: typeof AdminSettingsPricingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings/plans': {
      id: '/admin/settings/plans'
      path: '/settings/plans'
      fullPath: '/admin/settings/plans'
      preLoaderRoute: typeof AdminSettingsPlansRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/banks/$bankId/upload': {
      id: '/admin/banks/$bankId/upload'
      path: '/$bankId/upload'
      fullPath: '/admin/banks/$bankId/upload'
      preLoaderRoute: typeof AdminBanksBankIdUploadRouteImport
      parentRoute: typeof AdminBanksRoute
    }
    '/admin/banks/$bankId/questions': {
      id: '/admin/banks/$bankId/questions'
      path: '/$bankId/questions'
      fullPath: '/admin/banks/$bankId/questions'
      preLoaderRoute: typeof AdminBanksBankIdQuestionsRouteImport
      parentRoute: typeof AdminBanksRoute
    }
  }
}

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppBanksRoute: typeof AppBanksRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppLeaderboardRoute: typeof AppLeaderboardRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSessionsRoute: typeof AppSessionsRoute
  AppSubscriptionRoute: typeof AppSubscriptionRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppBanksRoute: AppBanksRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppLeaderboardRoute: AppLeaderboardRoute,
  AppProfileRoute: AppProfileRoute,
  AppSessionsRoute: AppSessionsRoute,
  AppSubscriptionRoute: AppSubscriptionRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AdminBanksRouteChildren {
  AdminBanksBankIdQuestionsRoute: typeof AdminBanksBankIdQuestionsRoute
  AdminBanksBankIdUploadRoute: typeof AdminBanksBankIdUploadRoute
}

const AdminBanksRouteChildren: AdminBanksRouteChildren = {
  AdminBanksBankIdQuestionsRoute: AdminBanksBankIdQuestionsRoute,
  AdminBanksBankIdUploadRoute: AdminBanksBankIdUploadRoute,
}

const AdminBanksRouteWithChildren = AdminBanksRoute._addFileChildren(
  AdminBanksRouteChildren,
)

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminBanksRoute: typeof AdminBanksRouteWithChildren
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminFlagsRoute: typeof AdminFlagsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminSubscriptionsRoute: typeof AdminSubscriptionsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminSettingsPlansRoute: typeof AdminSettingsPlansRoute
  AdminSettingsPricingRoute: typeof AdminSettingsPricingRoute
  AdminSettingsSystemRoute: typeof AdminSettingsSystemRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminBanksRoute: AdminBanksRouteWithChildren,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminFlagsRoute: AdminFlagsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminSubscriptionsRoute: AdminSubscriptionsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminSettingsPlansRoute: AdminSettingsPlansRoute,
  AdminSettingsPricingRoute: AdminSettingsPricingRoute,
  AdminSettingsSystemRoute: AdminSettingsSystemRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface QuizSessionIdRouteChildren {
  QuizSessionIdResultsRoute: typeof QuizSessionIdResultsRoute
  QuizSessionIdReviewRoute: typeof QuizSessionIdReviewRoute
}

const QuizSessionIdRouteChildren: QuizSessionIdRouteChildren = {
  QuizSessionIdResultsRoute: QuizSessionIdResultsRoute,
  QuizSessionIdReviewRoute: QuizSessionIdReviewRoute,
}

const QuizSessionIdRouteWithChildren = QuizSessionIdRoute._addFileChildren(
  QuizSessionIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  QuizSessionIdRoute: QuizSessionIdRouteWithChildren,
  QuizConfigureBankIdRoute: QuizConfigureBankIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
